In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cross_validation import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import log_loss
%run  T.ipynb


In [8]:
#Random Forest Regression for the original data

In [9]:
X = final[["ATMs per 1000 Adults", "iPhone Users", "Starbucks Locations"]]
y = final[["GEI Score"]]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

ranf = RandomForestRegressor(n_estimators=25)
ranf.fit(X_train, y_train.values.ravel())

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=25, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [10]:
y_pred = ranf.predict(X_test)
y_pred

array([ 30.2  ,  35.308,  55.512,  53.304,  47.084,  58.936,  42.42 ,
        29.152,  62.124,  41.328,  46.94 ,  59.94 ,  47.876,  47.256,
        25.056,  45.736,  56.008,  22.752])

In [11]:
plt.plot(y_pred, y_test, "o")
plt.plot([20, 90], [20, 90], 'k-')
plt.show()

In [13]:
ranf.score(X_test,y_test)
#The result is wierd and we change the method to classifer

-0.037871349524049247

In [14]:
#Random Forest Classfier for changing the result data into binary data

In [15]:
# Convert the GEI Score into a binary output
finalb = final.sort_values(["GEI Score"], ascending=False)
finalb = final.reset_index(drop=True)

# Any country with GEI score above 42.2 is considered a potential country
finalb['GEI Score'] = finalb['GEI Score'].apply(lambda x: 1 if x >= 42.2 else 0)
finalb['GEI Score'] = finalb["GEI Score"].astype(bool)
finalb['GEI Score'] = finalb["GEI Score"].astype(int)

In [16]:
#Split data
X = finalb[["ATMs per 1000 Adults", "iPhone Users", "Starbucks Locations"]]
y = finalb[["GEI Score"]]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [17]:
#Random Forest Classifer
ranf = RandomForestClassifier(n_estimators=25)
ranf.fit(X_train, y_train.values.ravel())

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [18]:
y_pred = ranf.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0])

In [19]:
a = np.array(y_pred)
b = np.array(y_test)
df = np.column_stack((a,b))
df

array([[0, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 1],
       [1, 1],
       [1, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [0, 1]])

In [20]:
ranf.score(X_test,y_test)

0.55555555555555558